version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: "yahya"
      POSTGRES_PASSWORD: "yahyaPASSWORD"
      POSTGRES_DB: "yahya_db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d yahya_db -U yahya"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # .NET 8 Backend Service
  backend:
    container_name: dotnet
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - ./server:/usr/src/app
      - /app/bin
      - /app/obj
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy  # Wait for PostgreSQL to be healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Next.js Frontend Service
  frontend:
    container_name: next
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

  # Nginx Reverse Proxy Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/.next:/usr/share/nginx/html/_next
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  node_modules:
