# Use the .NET SDK image for development
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set the working directory
WORKDIR /usr/src/app

# Install the dotnet-ef tool
RUN dotnet tool install --global dotnet-ef

# Ensure the global tools path is added to the PATH environment variable
ENV PATH="$PATH:/root/.dotnet/tools"

# Copy the csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./

# Expose the development port
EXPOSE 5286

# Add a script to handle migrations and start the app
COPY ./start.dev.sh .
RUN sed -i 's/\r$//g' /usr/src/app/start.dev.sh
RUN chmod +x /usr/src/app/start.dev.sh

# Start the application
# CMD ["sleep", "infinity"]
ENTRYPOINT ["/usr/src/app/start.dev.sh"]
